version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/thema:/var/www/html/wp-content/themes/thema
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: jojo
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  wordpress:
  db: