version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ../wordpress/thema:/var/www/html/wp-content/themes/thema
      - ./downlaods:/var/www/html/wp-content/downloads
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: jojo
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db:/var/lib/mysql
  sync-service:
    depends_on:
      - db
    build:
      context: ./py-project
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      REMOTE_SERVER: db
      RM_USER: exampleuser
      RM_PASS: examplepass
      RM_DB: exampledb
      LOCAL_SERVER: db
      LO_USER: exampleuser
      LO_PASS: examplepass
      LO_DB: exampledb
    volumes:
      - ./downloads:/usr/src/app/downloads
volumes:
  #wordpress:
  db: